### ISSUE TITLE
vcf2smartpca.py from GATK haplotypecaller

### ISSUE THREAD

**Issue by peterdfields** [DeWitP/SFG#1]
Hi

I'm trying to use the vcf2smartpca.py script but I'm getting a strange error:

Traceback (most recent call last):
  File "/home/peter/popgen/SFG/scripts/vcf2smartpca.py", line 200, in <module>
    list_headers, list_lines = genos4smart(headers, all_gens, pops)
  File "/home/peter/popgen/SFG/scripts/vcf2smartpca.py", line 58, in genos4smart
    thisline=[indiv, pops[indiv]]
KeyError: 'Ind1'

I used GATK haplotypecaller and the gvcf option. I'm not quite sure what might be wrong with the formatting. Let me know if additional info might be useful to troubleshoot the error.

**Comment by DeWitP** [comment]
Hi Peter, I talked to Jason Ladner, who wrote the script. He'd be happy to try to help you out if you contact him at jtladner@gmail.com
All the best,
Pierre

**Comment by peterdfields** [comment]
Thanks! I'll do that now. I'll go ahead and close the issue for now.
